---
commitizen:
  bump_message: 'bump(mqtt_cxx): $current_version -> $new_version'
  pre_bump_hooks: python ../../ci/changelog.py esp_mqtt_cxx
  tag_format: mqtt_cxx-v$version
  version: 0.4.0
  version_files:
  - idf_component.yml
